[package]
name = "connect4xyz"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = "0.11.3"


[profile.release]
opt-level = 2
lto = true

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
