[build]
pattern_script = "<script type=\"module\">import init, { new_game } from '{base}{js}'; init('{base}{wasm}'); document.addEventListener('DOMContentLoaded', () => { document.getElementById('NewGameButton').addEventListener('click', () => { new_game(); }); }); </script>"
dist = "./docs"
public_url = "./"
