[build]

pattern_script = "<script type=\"module\">import init, { new_game, nostr_login, guest_login } from '{base}{js}'; init('{base}{wasm}'); document.addEventListener('DOMContentLoaded', () => { document.getElementById('NewGameButton').addEventListener('click', () => { new_game(); }); document.getElementById('NostrLogin').addEventListener('click', () => { nostr_login(); }); document.getElementById('GuestLogin').addEventListener('click', () => { guest_login(); }); });</script>"
dist = "./docs"
public_url = "./"
